import { NavigationUserMenuProps } from './NavigationUserMenu';

export const resolveDropdownWithButtonProps = (
  props: NavigationUserMenuProps,
) => {
  const {
    activeIndex,
    id,
    options,
    maxHeight,
    disabled,
    showDropdownActions,
    actionCancelText,
    actionConfirmText,
    actionText,
    actionClearText,
    actionCustomButtonProps,
    showActionShowTopBar,
    isMatchInputValue,
    inputPosition,
    placement,
    customWidth,
    sameWidth,
    listboxId,
    listboxLabel,
    onClose,
    onOpen,
    open,
    onVisibilityChange,
    onSelect,
    onActionConfirm,
    onActionCancel,
    onActionCustom,
    onActionClear,
    onItemHover,
    zIndex,
    status,
    loadingText,
    emptyText,
    emptyIcon,
    followText,
    disablePortal,
    onReachBottom,
    onLeaveBottom,
    mode,
    value,
    ...buttonProps
  } = props;

  return {
    dropdownProps: {
      activeIndex,
      id,
      options,
      maxHeight,
      disabled,
      showDropdownActions,
      actionCancelText,
      actionConfirmText,
      actionText,
      actionClearText,
      actionCustomButtonProps,
      showActionShowTopBar,
      isMatchInputValue,
      inputPosition,
      placement,
      customWidth,
      sameWidth,
      listboxId,
      listboxLabel,
      onClose,
      onOpen,
      open,
      onVisibilityChange,
      onSelect,
      onActionConfirm,
      onActionCancel,
      onActionCustom,
      onActionClear,
      onItemHover,
      zIndex,
      status,
      loadingText,
      emptyText,
      emptyIcon,
      followText,
      disablePortal,
      onReachBottom,
      onLeaveBottom,
      mode,
      value,
    },
    buttonProps,
  };
};
