name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          check-latest: true

      - name: Install Yarn
        run: npm i -g yarn

      - name: Install Dependencies
        run: yarn

      - name: Test
        run: yarn test
